### ISSUE TITLE
CacheStorage is not available in Deno Deploy

### ISSUE THREAD

**Issue by pixeleet** [lumeland/imagemagick-deno#6]
Was playing around with trying to get a `next/image` like component for deno/fresh.
Needed to manually patch `mod.ts` to be able to get deploy working. 

It seems to be that `CacheStorage` is not available in Deno Deploy.

**Comment by reggi** [comment]
Facing the same issue:

```
ReferenceError: caches is not defined
    at initialize (https://deno.land/x/imagemagick_deno@0.0.22/mod.ts:12:17)
    at file:///src/main.ts:6:7
```

**Comment by oscarotero** [comment]
I just released 0.0.24 that detects the availability of `caches` before using it. It should work on Deno Deploy now.

**Comment by reggi** [comment]
@oscarotero wow fast turn around thanks. I'm trying to wrap my head around how this should work. Yesterday I just caved and downloaded the wasm file and added it to my repo that way I don't have to worry about cold-start having to download the file in real-time. With your solution will instances be downloading this binary often?

**Comment by oscarotero** [comment]
@reggi [As you can see](https://github.com/lumeland/imagemagick-deno/blob/main/deno/mod.ts#L12-L16), it only downloads the binary file if `caches` does not exist. This works both in deno-cli (in which cache will be used) and deno deploy (that won't be cached, but I guess it's not a big deal because the script only starts once).

I hope [Deno Deploy implements CacheStorage](https://github.com/denoland/deploy_feedback/issues/74) soon (although I doubt it).
